require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/**/**'
    - 'Guardfile'

inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 120
Style/Copyright:
  Enabled: false

